package db

import (
	"bca_crawler/internal/utils"
	"fmt"

	"github.com/jmoiron/sqlx"
)

const schema_pg = `
CREATE TABLE IF NOT EXISTS announcements (
	id SERIAL PRIMARY KEY,
	ann_id INTEGER UNIQUE,
	title TEXT,
	link TEXT UNIQUE,
	company_name TEXT,
	stock_name TEXT,
	date_posted TIMESTAMP,
	category TEXT,
	ref_number TEXT,
	content TEXT,
	attachments TEXT
);
CREATE INDEX IF NOT EXISTS idx_ann_date_posted ON announcements(date_posted);


CREATE TABLE IF NOT EXISTS entities ( 
    id SERIAL PRIMARY KEY,
    primary_perm_id INTEGER,
    secondary_perm_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100001 INCREMENT BY 1),
    display_name TEXT NOT NULL,
    name TEXT,
    salutation TEXT,
    stock_code TEXT,
    birth_year INTEGER,
    gender TEXT,
    nationality TEXT,
    ori_name TEXT,
    alias_name TEXT,
    new_ic TEXT,
    related_perm JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS boardroom_changes (
    id SERIAL PRIMARY KEY,
    ann_id INTEGER UNIQUE,
    company_name TEXT,
    stock_code TEXT,
    person_name TEXT,
    person_title TEXT,
    person_birth_year INTEGER,
    person_gender TEXT,
    person_nationality TEXT,
    date_announced DATE,
    date_of_change DATE,
    designation TEXT,
    previous_position TEXT,
    remarks TEXT,
    directorate TEXT,
    type_of_change TEXT,
    related_perm INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS backgrounds (
    id SERIAL PRIMARY KEY,
    perm_id INTEGER NOT NULL,
    qualification TEXT,
    working_experience TEXT,
    directorships TEXT,
    family_relationship TEXT,
    conflict_of_interest TEXT,
    interest_in_securities TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_backgrounds_perm_id ON backgrounds(perm_id);

`

// DriverType represents supported database drivers
type DriverType string

const (
	DriverPostgres DriverType = "postgres"
)

// Setup initializes and verifies the database schema
func Setup(connStr string, driver DriverType) (*sqlx.DB, error) {
	var db *sqlx.DB
	var err error

	switch driver {
	case DriverPostgres:
		db, err = sqlx.Open("postgres", connStr+"?sslmode=disable")
		if err != nil {
			return nil, err
		}

		if _, err := db.Exec(schema_pg); err != nil {
			db.Close()
			return nil, err
		}
	}

	utils.Logger.Infof("Database initialized and schema verified (%s)", connStr)
	return db, nil
}

// Connect connects to an existing PostgreSQL database without altering schema
func Connect(connStr string, driver DriverType) (*sqlx.DB, error) {
	var db *sqlx.DB
	var err error

	switch driver {
	case DriverPostgres:
		db, err = sqlx.Open("postgres", connStr+"?sslmode=disable")
	}

	if err != nil {
		return nil, fmt.Errorf("open db: %w", err)
	}
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("ping db: %w", err)
	}
	utils.Logger.Infof("Connected to database: %s", connStr)
	return db, nil
}
