package db

import (
	"bca_crawler/internal/utils"
	"fmt"

	"github.com/jmoiron/sqlx"
)

const schema_pg = `
CREATE TABLE IF NOT EXISTS announcements (
	id SERIAL PRIMARY KEY,
	ann_id INTEGER UNIQUE,
	title TEXT,
	link TEXT UNIQUE,
	company_name TEXT,
	stock_name TEXT,
	date_posted TIMESTAMP,
	category TEXT,
	ref_number TEXT,
	content TEXT,
	attachments TEXT
);
CREATE INDEX IF NOT EXISTS idx_ann_date_posted ON announcements(date_posted);


CREATE TABLE IF NOT EXISTS entities ( 
    id SERIAL PRIMARY KEY,
    primary_perm_id INTEGER,
    secondary_perm_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100001 INCREMENT BY 1),
    display_name TEXT NOT NULL,
    name TEXT,
    salutation TEXT,
    stock_code TEXT,
    birth_year INTEGER,
    gender TEXT,
    nationality TEXT,
    ori_name TEXT,
    alias_name TEXT,
    new_ic TEXT,
    img_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS entities_role (
	id SERIAL PRIMARY KEY,
	perm_id INTEGER NOT NULL,
	company_name TEXT,
	stock_name TEXT,
	date_appointed DATE,
	date_resigned DATE,
	category TEXT,
	role_name TEXT NOT NULL,
	promoted BOOL DEFAULT FALSE,
	alternative BOOL DEFAULT FALSE,
	independentcy BOOL DEFAULT FALSE,
	executive BOOL DEFAULT FALSE,
	chairmanship BOOL DEFAULT FALSE,
	date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(perm_id, stock_name, role_name, date_appointed)
);


CREATE TABLE IF NOT EXISTS boardroom_changes (
    id SERIAL PRIMARY KEY,
    ann_id INTEGER UNIQUE,
    company_name TEXT,
    stock_code TEXT,
    person_name TEXT,
    person_title TEXT,
    person_birth_year INTEGER,
    person_gender TEXT,
    person_nationality TEXT,
    date_announced DATE,
    date_of_change DATE,
    designation TEXT,
    previous_position TEXT,
    remarks TEXT,
    directorate TEXT,
    type_of_change TEXT,
    related_perm INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS backgrounds (
    id SERIAL PRIMARY KEY,
    perm_id INTEGER NOT NULL,
    qualification TEXT,
    working_experience TEXT,
    directorships TEXT,
    family_relationship TEXT,
    conflict_of_interest TEXT,
    interest_in_securities TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_backgrounds_perm_id ON backgrounds(perm_id);
 

CREATE TABLE IF NOT EXISTS company ( 
    id SERIAL PRIMARY KEY,
    primary_perm_id INTEGER,
    secondary_perm_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 300001 INCREMENT BY 1),
    company_name TEXT,
    reg_no TEXT,
    reg_no_old TEXT,
    date_incorporation TEXT,
    incorporate_under TEXT,
    stock_code TEXT,
    about TEXT,
    industry TEXT,
    website TEXT,
    address TEXT,
    phone TEXT,
    fax TEXT,
    ir_contact TEXT,
    group_structure TEXT,
    industry_overview TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS stocks (
    id SERIAL PRIMARY KEY,
    stock_code VARCHAR(20) NOT NULL UNIQUE,
    bursa_id INT,
    bursa_code VARCHAR(50),
    "name" TEXT,
    sector TEXT,
    sub_sector TEXT,
    "type" TEXT,
    shariah BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    stock_name TEXT,
    board TEXT,
    about TEXT,
    website TEXT,
    address TEXT,
    phone TEXT,
    fax TEXT,
    management JSONB,
    ownership JSONB,
    top_investors JSONB,
    insiders JSONB,
    new_name TEXT,
    date_new_name DATE,
    active BOOL,
    reg_no TEXT,
    reg_no_old TEXT
);


CREATE TABLE IF NOT EXISTS shareholding_change (
    id SERIAL PRIMARY KEY,
    ann_id INTEGER NOT NULL,
    stock_code VARCHAR(20) NOT NULL,
    company_name TEXT,
    change_type TEXT,
    person_name TEXT,
    person_address TEXT,
    person_nationality TEXT,
    company_no TEXT,
    security_description TEXT,
    registered_holder TEXT,
    registered_holder_address TEXT,
    transaction_type TEXT,
    transaction_desc TEXT,
    currency TEXT,
    date_of_change DATE,
    date_interest_acquired DATE,
    date_of_cessation DATE,
    securities_changed BIGINT,
    price_transacted NUMERIC(18,6),
    nature_of_interest TEXT,
    circumstances TEXT,
    consideration TEXT,
    direct_units BIGINT,
    direct_percent NUMERIC(10,4),
    indirect_units BIGINT,
    indirect_percent NUMERIC(10,4),
    total_securities BIGINT,
    date_of_notice DATE,
    date_notice_received DATE,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

`

// DriverType represents supported database drivers
type DriverType string

const (
	DriverPostgres DriverType = "postgres"
)

// Setup initializes and verifies the database schema
func Setup(connStr string, driver DriverType) (*sqlx.DB, error) {
	var db *sqlx.DB
	var err error

	switch driver {
	case DriverPostgres:
		db, err = sqlx.Open("postgres", connStr+"?sslmode=disable")
		if err != nil {
			return nil, err
		}

		if _, err := db.Exec(schema_pg); err != nil {
			db.Close()
			return nil, err
		}
	}

	utils.Logger.Infof("Database initialized and schema verified (%s)", connStr)
	return db, nil
}

// Connect connects to an existing PostgreSQL database without altering schema
func Connect(connStr string, driver DriverType) (*sqlx.DB, error) {
	var db *sqlx.DB
	var err error

	switch driver {
	case DriverPostgres:
		db, err = sqlx.Open("postgres", connStr+"?sslmode=disable")
	}

	if err != nil {
		return nil, fmt.Errorf("open db: %w", err)
	}
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("ping db: %w", err)
	}
	utils.Logger.Infof("Connected to database: %s", connStr)
	return db, nil
}
